In [4]:
import numpy as np

# 假设你的文件名是'output_file.npz'
file_name = 'patent_D_embeddings_0.npz'

# 使用np.load()函数来读取npz文件
with np.load(file_name) as data:
    # 列出文件中所有数组的名称
    print(data.files)
    
    # 访问embeddings和ids数组
    embeddings_array = data['embeddings']
    ids_array = data['ids']
    
    # 打印数组或执行其他操作
    print("Embeddings Array:")
    print(embeddings_array)
    
    print("IDs Array:")
    print(ids_array)

['embeddings', 'ids']
Embeddings Array:
[[ 0.002491   -0.00783539 -0.05648804 ... -0.00778198  0.0060463
  -0.02053833]
 [ 0.01200104 -0.04959106  0.00019848 ... -0.02311707  0.00577545
  -0.04223633]
 [-0.03353882  0.03778076 -0.02146912 ... -0.0076561  -0.03607178
  -0.08044434]
 ...
 [ 0.00063181 -0.00747681 -0.06561279 ... -0.03771973 -0.01292419
  -0.05895996]
 [ 0.00093842 -0.00125694 -0.00811768 ...  0.00361443 -0.00070763
  -0.03161621]
 [ 0.02799988  0.00341797  0.02339172 ...  0.0322876   0.0044136
  -0.09960938]]
IDs Array:
[41947446 41950716 41950838 ... 38759163 38763730 38766056]

In [5]:
embeddings_array.shape

(341518, 512)

In [6]:
min(ids_array)

86

In [7]:
import pandas as pd
df = pd.read_csv("patent_data_D_cleaned.csv")
df.head()

,id,title,main_ipc,brief
0,41947446,风道系统、滚筒组件、干衣设备及控制方法,D06F58/20,风道系统、滚筒组件、干衣设备及控制方法，涉及干衣设备技术领域，解决了现有技术中存在的热泵干衣...
1,41950716,用于造纸机车速联锁系统的高压清洗结构,D06B1/02,用于造纸机车速联锁系统的高压清洗结构，包括高压喷淋管和摆动器，摆动器的输出端处设有螺杆，螺杆...
2,41950838,一种熔体一步法生产线的生产制作流程,D01F8/14,熔体一步法生产线的生产制作流程，具体流程步骤如下：S1、高粘半消光PET切片经过干燥组件系统...
3,41951009,一种便于卡接的柔性打包带结构加工用裁剪设备,D06H7/02,便于卡接的柔性打包带结构加工用裁剪设备，涉及裁剪设备技术领域，为解决现有的裁剪设备在使用的过...
4,41952143,一种球形结构晾衣架,D06F57/00,本实用新型提供一种球形结构晾衣架，涉及晾衣架技术领域，包括两个圆环框架，每个所述圆环框架的相...

In [8]:
df.tail()

,id,title,main_ipc,brief
341513,38747850,一种具有辅助画线结构的服装设计用画线定型装置,D06H1/04,具有辅助画线结构的服装设计用画线定型装置，涉及服装设计技术领域，为了解决由于布料有一定的韧性...
341514,38754872,一种用于缝制鞋套松紧带的缝纫机,D05B35/06,本实用新型属于缝纫机技术领域，特别涉及一种用于缝制鞋套松紧带的缝纫机。所述缝纫机包括缝纫机主...
341515,38759163,一种聚乙烯醇原液着色用水性色浆及其制备方法,D01F1/04,聚乙烯醇原液着色用水性色浆及其制备方法，属于水性色浆技术领域。本发明的水性色浆包括以下原料：...
341516,38763730,用于洗涤设备的控制方法,D06F33/32,家电技术领域，具体提供一种用于洗涤设备的控制方法，现有洗涤设备重新上电后直接运行掉电之前的操...
341517,38766056,一种钢丝绳编织机,D04C3/46,钢丝绳编织机技术领域，公开了一种钢丝绳编织机，包括工作台、驱动装置和编织小车，工作台上设有腰...

In [2]:
import cupy as cp
import time
cp.cuda.Device(2).use()
# 生成7,000,000 x 512的大矩阵
start_time = time.time()
A = cp.random.random((860000, 512)).astype(cp.float32)
print(f"生成大矩阵耗时: {time.time() - start_time:.2f}秒")
print(f"大矩阵形状: {A.shape}, 内存占用: {A.nbytes / (1024**3):.2f} GB")

# 生成10 x 512的查询矩阵
B = cp.random.random((100, 512)).astype(cp.float32)
print(f"查询矩阵形状: {B.shape}")

# 执行点积操作
start_time = time.time()
result = cp.dot(A, B.T)  # 结果将是7,000,000 x 10的矩阵
cp.cuda.Stream.null.synchronize()  # 确保计算完成
dot_time = time.time() - start_time

print(f"点积计算耗时: {dot_time:.2f}秒")
print(f"结果矩阵形状: {result.shape}")
print(f"结果矩阵前5行:\n{result[:5]}")

生成大矩阵耗时: 0.04秒
大矩阵形状: (860000, 512), 内存占用: 1.64 GB
查询矩阵形状: (100, 512)
点积计算耗时: 0.02秒
结果矩阵形状: (860000, 100)
结果矩阵前5行:
[[122.80902  123.57507  132.34059  126.63123  129.23048  134.31705
  127.54985  123.84535  136.2579   127.354416 131.97687  134.87029
  128.48079  130.48706  125.674225 132.39885  134.46066  136.16797
  122.36594  126.83964  132.5158   128.47568  130.79915  132.19623
  126.46248  131.71622  131.55435  137.37442  125.70055  136.51009
  125.99857  128.62599  132.14691  126.771736 131.71503  129.27266
  128.70064  127.5236   132.1939   130.21187  127.523254 125.27825
  128.55707  133.56512  127.395836 128.02313  132.21767  127.55567
  129.48178  136.5259   134.32487  126.48962  133.17906  134.32764
  135.17027  128.27347  130.48558  131.73178  119.42966  128.09142
  133.7079   133.21797  128.23029  133.41382  130.74657  125.198784
  137.29451  124.82651  128.54187  127.35378  130.56992  131.25832
  129.7043   129.18121  126.3085   128.00475  130.08452  134.28702
  124.20561  123.2149   124.31522  129.46243  133.20023  133.482
  131.07642  130.28052  128.24623  125.607956 125.0171   131.10579
  131.17796  130.35185  133.61938  132.39873  128.37584  128.52292
  126.86757  126.52701  133.4091   127.83084 ]
 [118.21848  124.95018  127.65917  129.65257  128.14055  132.05324
  126.65085  124.84975  132.58965  130.56488  130.57228  129.88612
  124.651886 128.57326  124.46955  126.528496 131.38036  136.10188
  123.28289  127.026405 127.8413   124.72047  132.08885  124.97452
  120.66215  128.03027  130.23947  130.7508   123.55316  137.10616
  121.291985 126.99959  131.87654  125.02849  130.33751  129.54323
  128.28326  123.1895   124.47167  126.13863  122.12573  122.19707
  127.56939  130.481    126.42833  125.8848   127.78307  128.74977
  126.12823  133.5212   131.70143  125.21543  129.46422  132.6916
  130.89912  124.69205  125.756294 125.8231   121.97031  125.18179
  133.41115  131.03058  125.60605  128.78754  131.81146  121.18365
  136.80334  122.02382  132.39822  131.03563  132.85231  134.02933
  126.88904  123.51625  125.007256 125.01983  125.56425  130.24069
  123.49366  121.95837  120.506065 127.149254 128.45627  133.5507
  126.331696 130.17657  129.93056  121.52692  124.34831  133.12015
  132.0124   128.1088   132.32161  128.09796  126.602234 125.413445
  125.48103  120.918205 130.06519  124.54554 ]
 [117.44182  125.17319  127.93946  127.85154  129.16989  132.07234
  130.06105  126.09224  130.7651   124.32848  127.44114  130.0723
  123.20859  125.85363  124.021194 124.68075  128.1161   134.92981
  117.714806 123.73234  127.69566  126.19915  133.26968  131.36504
  122.29084  131.10692  128.74992  129.33975  125.00519  134.27626
  122.16423  122.35012  126.45303  126.845535 129.76964  126.94068
  123.00421  126.37702  127.149345 119.93118  125.65403  127.327934
  126.06149  131.15614  124.015015 126.35063  127.58506  125.388824
  126.49431  133.84854  128.16885  127.42594  131.48433  130.82774
  130.81158  123.085365 129.22154  125.907425 123.18341  126.24264
  131.87007  135.07762  127.167496 128.86269  129.05913  119.11686
  130.91295  124.38209  128.62701  124.656235 128.01845  129.10475
  130.27628  127.0809   123.78457  124.235115 127.38388  132.08034
  120.59629  119.44035  119.72175  124.98679  126.623375 132.06836
  125.13581  131.48444  126.085365 124.69954  127.297714 132.19293
  124.74959  130.09767  131.0819   126.95973  127.469574 122.76673
  124.742    124.47604  132.27489  123.692154]
 [125.418785 130.3833   132.43512  134.65866  136.0087   139.19362
  131.73053  132.49692  138.09796  132.32394  136.08751  138.90132
  132.20892  134.38095  129.58215  129.28595  135.90651  139.17662
  123.67358  129.14133  133.26831  130.7301   134.31152  134.81598
  131.46498  135.65442  136.56012  137.48105  129.25012  139.80597
  131.54741  133.68622  138.23083  127.99341  134.2283   130.90105
  132.62627  132.13722  134.36172  130.64053  132.02217  127.95812
  132.8896   137.38998  133.94572  130.19489  132.75087  129.1686
  135.16057  138.99193  138.68645  128.78888  136.38994  134.0489
  137.40593  132.87897  134.62398  138.71317  122.93044  133.8982
  135.46577  135.9075   128.30699  135.40018  138.6332   128.70078
  134.58617  126.956795 133.63704  133.96048  132.64119  133.84021
  135.5954   129.77766  129.43921  129.52003  132.2711   135.32173
  129.67245  131.99052  124.99666  131.98131  134.85573  139.9056
  132.19247  134.61281  131.99203  132.97836  130.67789  136.1602
  136.4824   137.45894  140.75516  130.7888   132.98167  126.81858
  131.46999  130.66438  138.43903  130.48045 ]
 [116.57879  121.178444 126.43064  127.653885 125.70718  125.53809
  125.6224   120.65661  129.26161  122.95935  126.89049  129.28972
  122.189095 125.307236 121.76552  123.0092   128.61432  128.19298
  121.04871  123.828064 124.97541  119.96961  126.48671  126.66821
  120.1553   122.26462  129.58643  125.93351  123.616196 127.56014
  119.846    125.4245   124.888824 122.647255 126.111084 125.40216
  123.033104 120.52296  127.732956 125.5329   123.22948  122.35638
  125.13471  128.12892  126.30176  122.09337  127.77507  123.32183
  127.69762  129.26291  128.87178  124.08567  123.666824 131.5089
  122.53188  122.67214  124.53051  124.5827   114.771385 122.92963
  126.80484  128.8157   121.93571  127.39182  126.50265  120.61679
  132.55345  119.39565  128.03273  124.47271  125.73476  127.60508
  125.308876 122.45445  122.50757  125.90071  121.422646 126.63691
  121.72831  120.743    116.18482  127.16338  130.78795  135.34187
  125.30201  127.77894  124.07688  124.06071  122.34966  126.71127
  126.47419  125.360954 131.57251  125.908585 126.56217  123.80471
  125.61437  121.69599  126.878876 123.69342 ]]

In [10]:
del A, B

In [ ]:
# 生成7,000,000 x 512的大矩阵
start_time = time.time()
C = cp.random.random((500000, 512)).astype(cp.float32)
print(f"生成大矩阵耗时: {time.time() - start_time:.2f}秒")
print(f"大矩阵形状: {C.shape}, 内存占用: {A.nbytes / (1024**3):.2f} GB")

OutOfMemoryError: Out of memory allocating 28,672,000,000 bytes (allocated so far: 43,008,000,000 bytes).

In [1]:
import pandas as pd
import numpy as np
import os
import gc
import time
import cupy as cp
from tqdm import tqdm
from cupyx.scipy.sparse import csr_matrix as cp_csr_matrix
from scipy.sparse import csr_matrix, save_npz, vstack, load_npz

def setup_gpu(gpu_id=0):
    """设置并初始化GPU"""
    cp.cuda.Device(gpu_id).use()
    device_name = cp.cuda.runtime.getDeviceProperties(gpu_id)['name'].decode()
    print(f"使用GPU {gpu_id}: {device_name}")

def load_data(patent_file, ipc_file):
    """加载和预处理专利数据"""
    print("正在读取数据文件...")
    patent_df = pd.read_csv(patent_file)
    ipc_df = pd.read_csv(ipc_file)
    
    print("正在合并IPC类别信息...")
    merged_df = pd.merge(
        patent_df,
        ipc_df,
        left_on='main_ipc',
        right_on='level_code',
        how='inner'
    )
    
    # 只保留需要的列以减少内存使用
    needed_columns = ['id', 'title', 'brief', 'level1_code', 'level2_code', 
                       'level3_code', 'level4_code', 'level5_code']
    return merged_df[needed_columns]

def create_feature_matrices(merged_df, weights):
    """为每个IPC级别创建特征矩阵"""
    print("进行高效预处理...")
    n = len(merged_df)
    feature_matrices = {}
    feature_matrices_gpu = {}
    
    for level, weight in weights.items():
        print(f"处理 {level}...")
        # 创建编码字典
        unique_values = merged_df[level].dropna().unique()
        code_to_idx = {code: idx for idx, code in enumerate(unique_values)}
        
        # 为每个专利创建行索引和列索引
        rows, cols, data = [], [], []
        
        for i, code in enumerate(merged_df[level]):
            if pd.notna(code):
                rows.append(i)
                cols.append(code_to_idx[code])
                data.append(1.0)  # 明确使用float类型
        
        # 创建稀疏矩阵，明确指定数据类型为float32
        feature_matrices[level] = csr_matrix((np.array(data, dtype=np.float32), 
                                             (np.array(rows), np.array(cols))), 
                                             shape=(n, len(code_to_idx)))
        
        # 转换为GPU稀疏矩阵
        feature_matrices_gpu[level] = cp_csr_matrix(feature_matrices[level])
        
        # # 保存编码字典以便后续使用
        # pd.DataFrame({'code': list(code_to_idx.keys()), 
        #               'index': list(code_to_idx.values())}).to_csv(
        #     f'{output_dir}/{level}_encoding.csv', index=False)
        
        # 清理内存
        del rows, cols, data
        gc.collect()
    
    return feature_matrices_gpu, n

# def process_batch_gpu(i, batch_size, n, feature_matrices_gpu, weights, output_dir, embeddings_array):
#     """处理单个批次的相似度计算"""
#     start_time = time.time()
#     print(f"处理批次 {i+1}/{(n + batch_size - 1) // batch_size}...")
#     start_i = i * batch_size
#     end_i = min((i + 1) * batch_size, n)
    
#     # 创建一个组合的相似度矩阵
#     combined_similarity = None
    
#     for level, weight in weights.items():
#         # 获取当前批次的特征矩阵（GPU版本）
#         batch_features = feature_matrices_gpu[level][start_i:end_i]
        
#         # 计算当前批次与所有专利的相似度（GPU加速）
#         level_similarity = batch_features.dot(feature_matrices_gpu[level].T)
        
#         # 应用权重
#         level_similarity = level_similarity.multiply(weight)
        
#         # 合并到总相似度矩阵
#         if combined_similarity is None:
#             combined_similarity = level_similarity
#         else:
#             combined_similarity = combined_similarity + level_similarity
    
#     # 对角线设为1（专利与自身的相似度）- 使用高效的矩阵操作替代循环
#     diagonal_indices = cp.arange(start_i, end_i)
#     row_indices = cp.arange(end_i - start_i)
#     combined_similarity[row_indices, diagonal_indices] = 1.0

#     # 计算摘要的embedding相似度
#     # 获取当前批次的摘要
#     # 计算摘要的embedding相似度（密集矩阵）
#     brief_similarity = cp.dot(embeddings_array[start_i:end_i], embeddings_array.T)

#     brief_similarity2 = cp.dot(embeddings_array[start_i:end_i], embeddings_array.T)
    
#     # 将combined_similarity从稀疏矩阵转换为密集矩阵，然后再相加
#     combined_similarity = combined_similarity.toarray()*0.4 + brief_similarity*0.4 + brief_similarity2*0.2 
    
    
#     # 将GPU结果转回CPU，并保存为稀疏矩阵
#     combined_similarity_cpu = combined_similarity.get()
#     # save_npz(f'{output_dir}/similarity_batch_{i}.npz', csr_matrix(combined_similarity_cpu))
    
#     end_time = time.time()
#     print(f"批次 {i+1} 处理完成，耗时: {end_time - start_time:.2f}秒")
#     return combined_similarity_cpu

# def process_batch_gpu(i, batch_size, n, feature_matrices_gpu, weights, output_dir, embeddings_array):
#     """处理单个批次的相似度计算并返回每行中值大于0.65的列索引"""
#     start_time = time.time()
#     print(f"处理批次 {i+1}/{(n + batch_size - 1) // batch_size}...")
#     start_i = i * batch_size
#     end_i = min((i + 1) * batch_size, n)
    
#     # 创建一个组合的相似度矩阵
#     combined_similarity = None
    
#     for level, weight in weights.items():
#         # 获取当前批次的特征矩阵（GPU版本）
#         batch_features = feature_matrices_gpu[level][start_i:end_i]
        
#         # 计算当前批次与所有专利的相似度（GPU加速）
#         level_similarity = batch_features.dot(feature_matrices_gpu[level].T)
        
#         # 应用权重
#         level_similarity = level_similarity.multiply(weight)
        
#         # 合并到总相似度矩阵
#         if combined_similarity is None:
#             combined_similarity = level_similarity
#         else:
#             combined_similarity = combined_similarity + level_similarity
    
#     # 对角线设为1（专利与自身的相似度）- 使用高效的矩阵操作替代循环
#     diagonal_indices = cp.arange(start_i, end_i)
#     row_indices = cp.arange(end_i - start_i)
#     combined_similarity[row_indices, diagonal_indices] = 1.0

#     # 计算摘要的embedding相似度
#     brief_similarity = cp.dot(embeddings_array[start_i:end_i], embeddings_array.T)
#     brief_similarity2 = cp.dot(embeddings_array[start_i:end_i], embeddings_array.T)
    
#     # 将combined_similarity从稀疏矩阵转换为密集矩阵，然后再相加
#     combined_similarity = combined_similarity.toarray()*0.4 + brief_similarity*0.4 + brief_similarity2*0.2 
    
#     # 在GPU上识别大于阈值的元素
#     similarity_mask = (combined_similarity > 0.8)

#     # 打印整个矩阵的最大值
#     print(combined_similarity.max())
    
#     # 将结果移到CPU上处理
#     similarity_mask_cpu = similarity_mask.get()
    
#     # 使用numpy的优化函数，为每一行查找满足条件的列索引
#     # 这比手动循环快得多
#     high_similarity_indices = [np.where(row_mask)[0].tolist() for row_mask in similarity_mask_cpu]
    
#     end_time = time.time()
#     print(f"批次 {i+1} 处理完成，耗时: {end_time - start_time:.2f}秒")
    
#     return high_similarity_indices

def process_batch_gpu(i, batch_size, n, feature_matrices_gpu, weights, brief_embeddings_array, title_embeddings_array, patent_ids):
    """处理单个批次的相似度计算并返回每行中值大于0.85的列索引及对应相似度值"""
    start_i = i * batch_size
    end_i = min((i + 1) * batch_size, n)
    
    # 创建一个组合的相似度矩阵
    combined_similarity = None
    
    for level, weight in weights.items():
        # 获取当前批次的特征矩阵（GPU版本）
        batch_features = feature_matrices_gpu[level][start_i:end_i]
        
        # 计算当前批次与所有专利的相似度（GPU加速）
        level_similarity = batch_features.dot(feature_matrices_gpu[level].T)
        
        # 应用权重
        level_similarity = level_similarity.multiply(weight)
        
        # 合并到总相似度矩阵
        if combined_similarity is None:
            combined_similarity = level_similarity
        else:
            combined_similarity = combined_similarity + level_similarity
    
    # 对角线设为1（专利与自身的相似度）- 使用高效的矩阵操作替代循环
    diagonal_indices = cp.arange(start_i, end_i)
    row_indices = cp.arange(end_i - start_i)
    combined_similarity[row_indices, diagonal_indices] = 1.0

    # 计算摘要的embedding相似度
    brief_similarity = cp.dot(brief_embeddings_array[start_i:end_i], brief_embeddings_array.T)
    title_similarity = cp.dot(title_embeddings_array[start_i:end_i], title_embeddings_array.T)
    
    # 将combined_similarity从稀疏矩阵转换为密集矩阵，然后再相加
    combined_similarity = combined_similarity.toarray()*0.4 + brief_similarity*0.4 + title_similarity*0.2
    
    # 在GPU上识别大于阈值的元素
    similarity_mask = (combined_similarity > 0.75)
    
    # 将相似度矩阵和掩码转移到CPU上处理
    similarity_cpu = combined_similarity.get()
    similarity_mask_cpu = similarity_mask.get()
    
    # 创建结果列表，同时包含索引和值
    high_similarity_results = []
    for row_idx in range(similarity_cpu.shape[0]):
        # 获取当前行中大于阈值的列索引
        col_indices = np.where(similarity_mask_cpu[row_idx])[0]
        # 获取这些位置的相似度值
        similarity_values = similarity_cpu[row_idx, col_indices]
        # 将索引和值打包在一起
        row_results = [(patent_ids[int(row_idx+start_i)], patent_ids[int(col_idx)], float(similarity_values[i])) 
                      for i, col_idx in enumerate(col_indices)]
        # 按相似度值降序排序
        row_results.sort(key=lambda x: x[2], reverse=True)
        high_similarity_results.append(row_results)
    
    return high_similarity_results

def merge_similarity_matrices(total_batches, output_dir):
    """合并所有批次的相似度矩阵"""
    print("合并相似度矩阵...")
    combined = None
    for i in range(total_batches):
        batch_sim = load_npz(f'{output_dir}/similarity_batch_{i}.npz')
        if combined is None:
            combined = batch_sim
        else:
            combined = vstack([combined, batch_sim])
    save_npz(f'{output_dir}/complete_similarity_matrix.npz', combined)
    print("合并完成，保存为 complete_similarity_matrix.npz")

# 加载专利的embedding npz
def load_patent_embeddings(file_name):
    data = cp.load(file_name)
    embeddings_array = data['embeddings']
    ids_array = data['ids']
    return embeddings_array, ids_array

def save_similiarity_results(similiarity_results, output_dir, ipc_code):
    # 将结果保存为csv文件
    pd.DataFrame(similiarity_results, columns=['patent_id', 'similar_patent_id', 'similarity_score']).to_csv(f'{output_dir}/similiarity_results_{ipc_code}.csv', index=False)

def main():
    # 设置GPU
    gpu_id = 0  # 修改这个值来选择不同的GPU
    setup_gpu(gpu_id)
    
    # 定义各层级权重
    weights = {
        # 'level1_code': 0.3,
        # 'level2_code': 0.2,
        'level3_code': 0.2,
        'level4_code': 0.3,
        'level5_code': 0.5
    }
    
    # 创建结果目录
    output_dir = 'similarity_results_gpu'
    os.makedirs(output_dir, exist_ok=True)
    
    # 加载数据
    merged_df = load_data('patent_data_D_cleaned.csv', 'ipc_categories_updated.csv')   ################
    
    # 创建索引映射表
    n = len(merged_df)
    if 'id' in merged_df.columns:
        index_mapping = pd.DataFrame({'row_idx': range(n), 'patent_id': merged_df['id']})
        index_mapping.to_csv(f'{output_dir}/index_mapping.csv', index=False)
    
    # 创建特征矩阵
    feature_matrices_gpu, n = create_feature_matrices(merged_df, weights, output_dir)

    # 加载专利的embedding npz
    embeddings_array, ids_array = load_patent_embeddings('patent_D_embeddings_0.npz')
    
    # 分批计算相似度矩阵
    print("开始计算分层相似度矩阵（GPU加速）...")
    batch_size = 2000  # GPU内存允许的情况下可以增加批次大小  ################
    total_batches = (n + batch_size - 1) // batch_size
    
    # 串行处理各个批次
    for i in range(total_batches):
        result = process_batch_gpu(i, batch_size, n, feature_matrices_gpu, weights, output_dir, embeddings_array)
        print(result)
    
    print(f"计算完成！所有结果已保存到 {output_dir} 目录下")
    
    # 合并结果
    merge_similarity_matrices(total_batches, output_dir)
    
    print("所有处理已完成，完整相似度矩阵已保存")

In [2]:
# 设置GPU
gpu_id = 1  # 修改这个值来选择不同的GPU
setup_gpu(gpu_id)

# 定义各层级权重
weights = {
    # 'level1_code': 0.3,
    # 'level2_code': 0.2,
    'level3_code': 0.2,
    'level4_code': 0.3,
    'level5_code': 0.5
}

# 创建结果目录
output_dir = 'similarity_results_gpu'
os.makedirs(output_dir, exist_ok=True)

# 加载数据
merged_df = load_data('patent_data_G06F_cleaned.csv', 'ipc_categories_updated.csv')   ################

# # 创建索引映射表
n = len(merged_df)
# if 'id' in merged_df.columns:
#     index_mapping = pd.DataFrame({'row_idx': range(n), 'patent_id': merged_df['id']})
#     index_mapping.to_csv(f'{output_dir}/index_mapping.csv', index=False)

# 创建特征矩阵
feature_matrices_gpu, n = create_feature_matrices(merged_df, weights, output_dir)

使用GPU 1: NVIDIA RTX 6000 Ada Generation
正在读取数据文件...
正在合并IPC类别信息...
进行高效预处理...
处理 level3_code...
处理 level4_code...
处理 level5_code...

In [2]:
import os
import glob

# 设置GPU
gpu_id = 0  # 修改这个值来选择不同的GPU
setup_gpu(gpu_id)

# 定义各层级权重
weights = {
    # 'level1_code': 0.3,
    # 'level2_code': 0.2,
    'level3_code': 0.2,
    'level4_code': 0.3,
    'level5_code': 0.5
}

patent_embedding_folder = "patent_embedding"
patent_data_folder = "patent_data"
output_dir = 'similarity_results_gpu'
# 获取所有npz文件路径
npz_files = glob.glob(os.path.join(patent_embedding_folder, "*.npz"))

IPC_3s = ['B05B']
# for file in npz_files:
#     # 从文件名中提取IPC_3代码
#     file_name = os.path.basename(file)
#     if "patent_brief_" in file_name and "_embeddings_0.npz" in file_name:
#         ipc_code = file_name.replace("patent_brief_", "").replace("_embeddings_0.npz", "")
#         IPC_3s.append(ipc_code)

# 进行保存的处理批次数量
save_batch = 1000

for ipc_code in IPC_3s:
    # 加载数据
    merged_df = load_data(os.path.join(patent_data_folder, 'patent_data_'+ipc_code+'_cleaned.csv'), 'ipc_categories_updated.csv')   ################
    # 创建索引映射表
    n = len(merged_df)
    # 创建特征矩阵
    feature_matrices_gpu, n = create_feature_matrices(merged_df, weights)
    # 加载专利的embedding npz
    brief_embeddings_array, brief_ids_array = load_patent_embeddings(os.path.join(patent_embedding_folder, 'patent_brief_'+ipc_code+'_embeddings_0.npz'))
    title_embeddings_array, title_ids_array = load_patent_embeddings(os.path.join(patent_embedding_folder, 'patent_title_'+ipc_code+'_embeddings_0.npz'))
    # 分批计算相似度矩阵
    print("开始计算分层相似度矩阵（GPU加速）...")
    batch_size = 500  # GPU内存允许的情况下可以增加批次大小  ################
    total_batches = (n + batch_size - 1) // batch_size

    similiarity_results = []
    # 串行处理各个批次
    for i in tqdm(range(total_batches), desc=f"Processing {ipc_code} batches"):
        result = process_batch_gpu(i, batch_size, n, feature_matrices_gpu, weights, brief_embeddings_array, title_embeddings_array, brief_ids_array.tolist())
        break
        for res in result:
            for r in res:
                similiarity_results.append(r)
        # 判断是否保存
        if i > 0 and i % save_batch == 0:
            save_similiarity_results(similiarity_results, output_dir, ipc_code+'_'+str(i))
            similiarity_results = []
    # 保存剩余结果
    # if len(similiarity_results) > 0:
    #     save_similiarity_results(similiarity_results, output_dir, ipc_code+'_'+str(total_batches))

使用GPU 0: NVIDIA RTX 6000 Ada Generation
正在读取数据文件...
正在合并IPC类别信息...
进行高效预处理...
处理 level3_code...
处理 level4_code...
处理 level5_code...
开始计算分层相似度矩阵（GPU加速）...

Processing B05B batches:   0%|          | 0/197 [00:03<?, ?it/s]

In [9]:
similiarity_results = []
for res in result:
    similiarity_results.extend(res)

In [10]:
similiarity_results[0]

(9939, 9939, 0.999981530372321)

In [18]:
42119107, 45650311, 45650139, 45648072, 45647246, 45646005
print(result[2][:100])
print(len(result[0]))

[(42119107, 45650311, 0.8973869331447076), (42119107, 45650139, 0.8774531701100955), (42119107, 45648072, 0.8965942072642065), (42119107, 45647246, 0.8911852054899554), (42119107, 45646005, 0.9130870927355772), (42119107, 45644043, 0.8908837377086457), (42119107, 45640337, 0.9082277726397934), (42119107, 45640156, 0.9149429084197891), (42119107, 45639553, 0.9157727607424022), (42119107, 45639529, 0.8870069415637317), (42119107, 45639181, 0.9050743914451231), (42119107, 45637493, 0.9080240550926789), (42119107, 45637371, 0.8675094708376492), (42119107, 45636625, 0.8876540889421564), (42119107, 45636344, 0.8492365436857086), (42119107, 45634963, 0.913491824808753), (42119107, 45634010, 0.8817330032981658), (42119107, 45633557, 0.9181368863355147), (42119107, 45633428, 0.9162752827365012), (42119107, 45631405, 0.907431073341104), (42119107, 45629251, 0.8768781468696716), (42119107, 45628257, 0.8833019038327337), (42119107, 45625564, 0.8820145785046862), (42119107, 45625175, 0.9121706073811708), (42119107, 45624740, 0.8917062872168402), (42119107, 45620623, 0.9169669377844003), (42119107, 45620581, 0.9259939429724228), (42119107, 45618238, 0.916468786625842), (42119107, 45614919, 0.8863394234911084), (42119107, 45614632, 0.8754162470818302), (42119107, 45613748, 0.9152882141308966), (42119107, 45613678, 0.9103923141029555), (42119107, 45613640, 0.8921960196535451), (42119107, 45613588, 0.9165618949309647), (42119107, 45613339, 0.8896079347024624), (42119107, 45612231, 0.88479386600211), (42119107, 45612109, 0.9218802423266425), (42119107, 45611837, 0.9019548103855868), (42119107, 45611637, 0.8947577770181112), (42119107, 45610561, 0.9320620459700648), (42119107, 45610526, 0.8846838079828557), (42119107, 45610057, 0.9044823593159379), (42119107, 45606332, 0.9055416060805329), (42119107, 45604053, 0.8772974926725481), (42119107, 45603854, 0.8959473055683476), (42119107, 45603567, 0.8874532666736286), (42119107, 45602531, 0.8756917051167875), (42119107, 45601651, 0.8947711265229032), (42119107, 45596729, 0.8968379475293887), (42119107, 45589327, 0.9029853139183159), (42119107, 45588849, 0.8852678723382269), (42119107, 45587948, 0.9067164417901039), (42119107, 45587529, 0.8714964581402), (42119107, 45586844, 0.8950904458482909), (42119107, 45585992, 0.9035095346587696), (42119107, 45584505, 0.9001491289988734), (42119107, 45584080, 0.9121177660387275), (42119107, 45582911, 0.8968589910026197), (42119107, 45581943, 0.908017014714244), (42119107, 45581439, 0.8954551064592579), (42119107, 45581215, 0.9203765498667962), (42119107, 45580953, 0.9096079288560304), (42119107, 45580797, 0.8898201535582757), (42119107, 45580783, 0.9024410206383437), (42119107, 45580596, 0.8934231017759202), (42119107, 45579461, 0.9089462276122049), (42119107, 45577703, 0.915068520655268), (42119107, 45577331, 0.9038947258932695), (42119107, 45576091, 0.8975251189672464), (42119107, 45575517, 0.9082858465483695), (42119107, 45575091, 0.9080789621374151), (42119107, 45574832, 0.8998596659272777), (42119107, 45574398, 0.8991279408101263), (42119107, 45574392, 0.9062159391935665), (42119107, 45572811, 0.9162331955138825), (42119107, 45572673, 0.9102378589279853), (42119107, 45572553, 0.8954088456824365), (42119107, 45572296, 0.8858270669045056), (42119107, 45572213, 0.9228669012021442), (42119107, 45571821, 0.9015070072992329), (42119107, 45570956, 0.9122297599463765), (42119107, 45569395, 0.9080172695943474), (42119107, 45568239, 0.8992212010922082), (42119107, 45567770, 0.9203820339930645), (42119107, 45567114, 0.8963925034971908), (42119107, 45565593, 0.9047619007136575), (42119107, 45563485, 0.8997652967345516), (42119107, 45560993, 0.9076930896251838), (42119107, 45557786, 0.8978028106737839), (42119107, 45557448, 0.8779407898833598), (42119107, 45556706, 0.9063025780316821), (42119107, 45553871, 0.8932688608028002), (42119107, 45552604, 0.8822485018897624), (42119107, 45552387, 0.8769622296713806), (42119107, 45551864, 0.9072177266013569), (42119107, 45551792, 0.889824045569685), (42119107, 45551630, 0.8960308077505943), (42119107, 45551615, 0.8990416338534942), (42119107, 45551094, 0.9066697077159234), (42119107, 45549035, 0.8898604684403382)]
12400

In [25]:
# 使用embeddings_array的前100行与embeddings_array进行点积运算
result = cp.dot(embeddings_array[:100], embeddings_array.T)
s_time = time.time()
print(result.shape)
e_time = time.time()
print(f"点积运算耗时: {e_time - s_time:.2f}秒")

(100, 341518)
点积运算耗时: 0.00秒

In [26]:
# 使用embeddings_array的100行与embeddings_array进行点积运算
result = cp.dot(embeddings_array[100:200], embeddings_array.T)
s_time = time.time()
print(result.shape)
e_time = time.time()
print(f"点积运算耗时: {e_time - s_time:.2f}秒")

(100, 341518)
点积运算耗时: 0.00秒

In [22]:
merged_df.iloc[823846]

id                                                      34424301
title                                        行为控制方法、装置、电子设备及存储介质
brief          本发明实施例提供一种行为控制方法、装置、电子设备及存储介质；方法包括：在目标行为发生时，获取...
level1_code                                                    G
level2_code                                                  G06
level3_code                                                 G06F
level4_code                                            G06F21/00
level5_code                                            G06F21/52
Name: 823846, dtype: object

In [9]:
merged_df.iloc[0]

id                                                           138
title                                      应用软件连接数据库的方法、装置、设备及介质
brief          本发明实施例公开了一种应用软件连接数据库的方法、装置、设备及介质。该方法包括：响应于目标应用...
level1_code                                                    G
level2_code                                                  G06
level3_code                                                 G06F
level4_code                                            G06F21/00
level5_code                                            G06F21/52
Name: 0, dtype: object

In [ ]:
E01F,H05B,C22C,C09D,B29B,G08B,C12Q,F15B,H04M,B25H,A41D,D06F,B41F,A01C,F16C,G01D,A47C,E05B,F21V,C01B,E21D,A47G,E02B,B60L,G01F,B22D,H01Q,B62B,F16B,G02F,A61L,F25D,B66B,G05D,B28B,F04B,C12M,E01C,B66F,C23C,B23D,B05C,C07C,A23L,E01D,B01F,A63B,G01C,H02M,A47L,G09B,A61H,H04B,C04B,B23B,G01S,H04R,G09F,C08L,H01B,H01F,B07B,E04F,C07D,A61G,B62D,G06V,F16H,B60R,B05B

In [ ]:
E06B,B25J,B32B,B26D,B66C,E04H,F04D,C12N,A61F,A47B,H01H,H02G,F26B,B23P,G05B,H02B,A01K,E21B,B25B,F21S,F16M,A47J,E04G,E02D,H02K,F16L,G02B,G01M,B02C,G01B,H04N,F16K,G06T,E04B,B23Q,B65B,H02J,B01J,A61M,B65H,A01G,C02F,H04W,F24F,B08B,B21D

In [ ]:
H01R,B24B,H04L,A61K,H05K,H01M,G01R,G06Q,B23K,H01L,B65D,A61B,B29C,B65G,B01D,G01N,G06F

In [6]:
import os
import glob

patent_embedding_folder = "patent_embedding"
patent_data_folder = "patent_data"
output_dir = 'similarity_results_gpu'
# 获取所有npz文件路径
npz_files = glob.glob(os.path.join(patent_embedding_folder, "*.npz"))

IPC_3s = []
for file in npz_files:
    # 从文件名中提取IPC_3代码
    file_name = os.path.basename(file)
    if "patent_brief_" in file_name and "_embeddings_0.npz" in file_name:
        ipc_code = file_name.replace("patent_brief_", "").replace("_embeddings_0.npz", "")
        IPC_3s.append(ipc_code)

In [1]:
import os
import glob
import pandas as pd
from tqdm import tqdm

similarity_dir = 'similarity_results_gpu'
# 获取similarity_results_gpu目录下的所有parquet文件
similarity_parquet_files = glob.glob(os.path.join(similarity_dir, "*.parquet"))
# 获取similarity_results_gpu目录下的所有csv文件
similarity_csv_files = glob.glob(os.path.join(similarity_dir, "*.csv"))

# parquet中包含的IPC
parquet_ipc_list = []
for file in similarity_parquet_files:
    parquet_ipc_list.append(os.path.basename(file).split("similiarity_results_")[1].split("_")[0])

# 有效的csv文件
similarity_csv_files = [file for file in similarity_csv_files if os.path.basename(file).split("similiarity_results_")[1].split("_")[0] not in parquet_ipc_list]

In [2]:
# csv中包含的IPC
ipc_list = []

for file in similarity_parquet_files: 
    ipc_list.append(os.path.basename(file).split("similiarity_results_")[1].split("_")[0])
for file in similarity_csv_files: 
    ipc_list.append(os.path.basename(file).split("similiarity_results_")[1].split("_")[0])

assert len(set(ipc_list)) == 644

In [4]:
# parquet结果列表
parquet_result_list = []
# 读取parquet文件为dataframe
for file in tqdm(similarity_parquet_files, desc="Processing parquet files"):
    tqdm.write(f"正在处理文件: {file}")
    df = pd.read_parquet(file)
    df = df[df['patent_id'] != df['similar_patent_id']]
    # 不使用 apply 的替代方案
    # 首先按 patent_id 和 similarity_score 排序
    df_sorted = df.sort_values(['patent_id', 'similarity_score'], ascending=[True, False])
    # 然后使用 groupby 和 head 获取每组前 100 条
    result = df_sorted.groupby('patent_id').head(100).reset_index(drop=True)
    parquet_result_list.append(result)

Processing parquet files:   0%|          | 0/275 [00:00<?, ?it/s]

正在处理文件: similarity_results_gpu/similiarity_results_B62K_25.parquet

Processing parquet files:   0%|          | 1/275 [00:01<06:57,  1.52s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C21D_40.parquet

Processing parquet files:   1%|          | 2/275 [00:06<15:52,  3.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04R_177.parquet

Processing parquet files:   1%|          | 3/275 [01:37<3:17:20, 43.53s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06V_190.parquet

Processing parquet files:   1%|▏         | 4/275 [04:19<6:47:05, 90.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06F_2000.parquet

Processing parquet files:   2%|▏         | 5/275 [11:36<16:08:58, 215.33s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06F_1000.parquet

Processing parquet files:   2%|▏         | 6/275 [18:50<21:38:12, 289.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01G_28.parquet

Processing parquet files:   3%|▎         | 7/275 [19:07<14:55:11, 200.42s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C07C_149.parquet

Processing parquet files:   3%|▎         | 8/275 [19:08<10:10:27, 137.18s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16H_191.parquet

Processing parquet files:   3%|▎         | 9/275 [19:47<7:51:23, 106.33s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60W_35.parquet

Processing parquet files:   4%|▎         | 10/275 [20:10<5:56:44, 80.77s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01S_25.parquet

Processing parquet files:   4%|▍         | 11/275 [20:14<4:11:48, 57.23s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C03B_35.parquet

Processing parquet files:   4%|▍         | 12/275 [20:33<3:19:42, 45.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G08B_105.parquet

Processing parquet files:   5%|▍         | 13/275 [23:37<6:21:47, 87.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60K_49.parquet

Processing parquet files:   5%|▌         | 14/275 [24:22<5:24:11, 74.53s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B21C_31.parquet

Processing parquet files:   5%|▌         | 15/275 [24:28<3:54:33, 54.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E01D_154.parquet

Processing parquet files:   6%|▌         | 16/275 [24:52<3:14:02, 44.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A43B_30.parquet

Processing parquet files:   6%|▌         | 17/275 [25:09<2:37:18, 36.58s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F21S_287.parquet

Processing parquet files:   7%|▋         | 18/275 [28:02<5:32:30, 77.63s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B21F_37.parquet

Processing parquet files:   7%|▋         | 19/275 [28:06<3:55:49, 55.27s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B63B_43.parquet

Processing parquet files:   7%|▋         | 20/275 [28:23<3:07:15, 44.06s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23K_873.parquet

Processing parquet files:   8%|▊         | 21/275 [32:29<7:22:41, 104.57s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B66F_141.parquet

Processing parquet files:   8%|▊         | 22/275 [32:55<5:41:49, 81.07s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B26F_30.parquet

Processing parquet files:   8%|▊         | 23/275 [33:07<4:13:07, 60.27s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B29C_1087.parquet

Processing parquet files:   9%|▊         | 24/275 [33:39<3:37:03, 51.88s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F01D_18.parquet

Processing parquet files:   9%|▉         | 25/275 [33:40<2:32:34, 36.62s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F04D_218.parquet

Processing parquet files:   9%|▉         | 26/275 [34:42<3:03:00, 44.10s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04W_383.parquet

Processing parquet files:  10%|▉         | 27/275 [39:22<7:54:55, 114.90s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01J_21.parquet

Processing parquet files:  10%|█         | 28/275 [39:24<5:33:41, 81.06s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B29B_105.parquet

Processing parquet files:  11%|█         | 29/275 [44:16<9:51:50, 144.35s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B28C_41.parquet

Processing parquet files:  11%|█         | 30/275 [44:52<7:36:53, 111.89s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E02F_32.parquet

Processing parquet files:  11%|█▏        | 31/275 [45:02<5:30:42, 81.32s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61G_188.parquet

Processing parquet files:  12%|█▏        | 32/275 [45:48<4:45:24, 70.47s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A23F_25.parquet

Processing parquet files:  12%|█▏        | 33/275 [49:43<8:04:08, 120.04s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16C_115.parquet

Processing parquet files:  12%|█▏        | 34/275 [49:58<5:55:12, 88.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60S_23.parquet

Processing parquet files:  13%|█▎        | 35/275 [50:11<4:22:50, 65.71s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23D_144.parquet

Processing parquet files:  13%|█▎        | 36/275 [50:21<3:15:07, 48.99s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06T_333.parquet

Processing parquet files:  13%|█▎        | 37/275 [52:58<5:23:26, 81.54s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B64C_35.parquet

Processing parquet files:  14%|█▍        | 38/275 [53:07<3:56:10, 59.79s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G03B_34.parquet

Processing parquet files:  14%|█▍        | 39/275 [53:18<2:56:57, 44.99s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47C_116.parquet

Processing parquet files:  15%|█▍        | 40/275 [53:35<2:24:26, 36.88s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B66C_212.parquet

Processing parquet files:  15%|█▍        | 41/275 [54:25<2:39:00, 40.77s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F04C_31.parquet

Processing parquet files:  15%|█▌        | 42/275 [54:36<2:02:49, 31.63s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01M_45.parquet

Processing parquet files:  16%|█▌        | 43/275 [55:19<2:15:18, 35.00s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47K_33.parquet

Processing parquet files:  16%|█▌        | 44/275 [55:27<1:44:20, 27.10s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C01G_19.parquet

Processing parquet files:  16%|█▋        | 45/275 [55:28<1:13:30, 19.17s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01J_27.parquet

Processing parquet files:  17%|█▋        | 46/275 [55:29<52:35, 13.78s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01S_176.parquet

Processing parquet files:  17%|█▋        | 47/275 [55:40<48:56, 12.88s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E05D_18.parquet

Processing parquet files:  17%|█▋        | 48/275 [56:03<1:00:51, 16.08s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B22F_33.parquet

Processing parquet files:  18%|█▊        | 49/275 [56:06<45:41, 12.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G16H_37.parquet

Processing parquet files:  18%|█▊        | 50/275 [56:08<33:32,  8.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F28D_41.parquet

Processing parquet files:  19%|█▊        | 51/275 [56:48<1:07:58, 18.21s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C03C_24.parquet

Processing parquet files:  19%|█▉        | 52/275 [56:56<56:11, 15.12s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F23G_28.parquet

Processing parquet files:  19%|█▉        | 53/275 [57:26<1:13:16, 19.80s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60G_18.parquet

Processing parquet files:  20%|█▉        | 54/275 [57:28<52:36, 14.28s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65G_1000.parquet

Processing parquet files:  20%|██        | 55/275 [1:06:32<10:35:53, 173.42s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23Q_352.parquet

Processing parquet files:  20%|██        | 56/275 [1:09:05<10:10:02, 167.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E05B_116.parquet

Processing parquet files:  21%|██        | 57/275 [1:09:11<7:11:51, 118.86s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E01F_101.parquet

Processing parquet files:  21%|██        | 58/275 [1:09:45<5:38:06, 93.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A63B_161.parquet

Processing parquet files:  21%|██▏       | 59/275 [1:10:27<4:40:08, 77.82s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H03K_27.parquet

Processing parquet files:  22%|██▏       | 60/275 [1:10:42<3:31:33, 59.04s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A41D_110.parquet

Processing parquet files:  22%|██▏       | 61/275 [1:16:26<8:35:34, 144.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C12Q_106.parquet

Processing parquet files:  23%|██▎       | 62/275 [1:16:33<6:06:47, 103.32s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B22D_125.parquet

Processing parquet files:  23%|██▎       | 63/275 [1:17:24<5:09:55, 87.71s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B62J_20.parquet

Processing parquet files:  23%|██▎       | 64/275 [1:17:26<3:37:08, 61.75s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F24D_34.parquet

Processing parquet files:  24%|██▎       | 65/275 [1:17:52<2:59:30, 51.29s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61K_717.parquet

Processing parquet files:  24%|██▍       | 66/275 [1:18:02<2:14:47, 38.70s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65D_1045.parquet

Processing parquet files:  24%|██▍       | 67/275 [1:18:04<1:36:10, 27.74s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B21B_35.parquet

Processing parquet files:  25%|██▍       | 68/275 [1:18:07<1:09:46, 20.22s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02B_263.parquet

Processing parquet files:  25%|██▌       | 69/275 [1:20:42<3:28:42, 60.79s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E21B_269.parquet

Processing parquet files:  25%|██▌       | 70/275 [1:22:40<4:25:53, 77.82s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G11C_25.parquet

Processing parquet files:  26%|██▌       | 71/275 [1:22:41<3:06:27, 54.84s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C07K_46.parquet

Processing parquet files:  26%|██▌       | 72/275 [1:22:44<2:13:26, 39.44s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F04B_136.parquet

Processing parquet files:  27%|██▋       | 73/275 [1:22:58<1:46:56, 31.77s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23C_23.parquet

Processing parquet files:  27%|██▋       | 74/275 [1:23:01<1:17:22, 23.10s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60L_124.parquet

Processing parquet files:  27%|██▋       | 75/275 [1:24:11<2:04:15, 37.28s/it]

正在处理文件: similarity_results_gpu/similiarity_results_D06F_111.parquet

Processing parquet files:  28%|██▊       | 76/275 [1:24:39<1:54:07, 34.41s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06F_2887.parquet

Processing parquet files:  28%|██▊       | 77/275 [1:29:26<6:03:30, 110.15s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B02C_320.parquet

Processing parquet files:  28%|██▊       | 78/275 [1:30:38<5:24:07, 98.72s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F24C_49.parquet

Processing parquet files:  29%|██▊       | 79/275 [1:31:42<4:48:38, 88.36s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C02F_372.parquet

Processing parquet files:  29%|██▉       | 80/275 [1:33:12<4:48:25, 88.74s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47F_33.parquet

Processing parquet files:  29%|██▉       | 81/275 [1:33:17<3:25:50, 63.66s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E03B_24.parquet

Processing parquet files:  30%|██▉       | 82/275 [1:33:33<2:39:00, 49.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G09G_43.parquet

Processing parquet files:  30%|███       | 83/275 [1:34:06<2:21:54, 44.35s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04F_186.parquet

Processing parquet files:  31%|███       | 84/275 [1:34:58<2:29:07, 46.85s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65G_1351.parquet

Processing parquet files:  31%|███       | 85/275 [1:37:47<4:24:05, 83.40s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B28D_35.parquet

Processing parquet files:  31%|███▏      | 86/275 [1:38:01<3:16:51, 62.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B01J_361.parquet

Processing parquet files:  32%|███▏      | 87/275 [1:38:54<3:07:04, 59.70s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C12M_138.parquet

Processing parquet files:  32%|███▏      | 88/275 [1:39:12<2:26:38, 47.05s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61B_1076.parquet

Processing parquet files:  32%|███▏      | 89/275 [1:39:37<2:05:39, 40.53s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E01B_20.parquet

Processing parquet files:  33%|███▎      | 90/275 [1:39:38<1:28:14, 28.62s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C30B_20.parquet

Processing parquet files:  33%|███▎      | 91/275 [1:39:38<1:02:04, 20.24s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B25J_209.parquet

Processing parquet files:  33%|███▎      | 92/275 [1:40:01<1:03:57, 20.97s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01H_239.parquet

Processing parquet files:  34%|███▍      | 93/275 [1:40:48<1:27:24, 28.82s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A45D_23.parquet

Processing parquet files:  34%|███▍      | 94/275 [1:40:53<1:05:01, 21.55s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B41F_112.parquet

Processing parquet files:  35%|███▍      | 95/275 [1:41:20<1:09:29, 23.16s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65D_1000.parquet

Processing parquet files:  35%|███▍      | 96/275 [1:42:22<1:44:17, 34.96s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E03F_45.parquet

Processing parquet files:  35%|███▌      | 97/275 [1:42:46<1:34:10, 31.74s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B21D_399.parquet

Processing parquet files:  36%|███▌      | 98/275 [1:44:24<2:31:43, 51.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B67C_21.parquet

Processing parquet files:  36%|███▌      | 99/275 [1:45:29<2:42:51, 55.52s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B66B_133.parquet

Processing parquet files:  36%|███▋      | 100/275 [1:45:54<2:15:36, 46.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E02D_304.parquet

Processing parquet files:  37%|███▋      | 101/275 [1:47:17<2:46:43, 57.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B66D_18.parquet

Processing parquet files:  37%|███▋      | 102/275 [1:47:35<2:11:08, 45.48s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F22B_18.parquet

Processing parquet files:  37%|███▋      | 103/275 [1:47:38<1:33:39, 32.67s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B41J_48.parquet

Processing parquet files:  38%|███▊      | 104/275 [1:48:23<1:43:38, 36.37s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C01B_119.parquet

Processing parquet files:  38%|███▊      | 105/275 [1:48:34<1:21:49, 28.88s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B07C_45.parquet

Processing parquet files:  39%|███▊      | 106/275 [1:49:26<1:40:54, 35.83s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H05B_102.parquet

Processing parquet files:  39%|███▉      | 107/275 [1:49:34<1:16:39, 27.38s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B09B_26.parquet

Processing parquet files:  39%|███▉      | 108/275 [1:49:46<1:03:42, 22.89s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01G_370.parquet

Processing parquet files:  40%|███▉      | 109/275 [1:55:02<5:06:26, 110.76s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C08L_184.parquet

Processing parquet files:  40%|████      | 110/275 [1:55:16<3:44:56, 81.79s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01K_36.parquet

Processing parquet files:  40%|████      | 111/275 [1:55:23<2:41:46, 59.18s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A63H_22.parquet

Processing parquet files:  41%|████      | 112/275 [1:55:23<1:53:15, 41.69s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A24F_37.parquet

Processing parquet files:  41%|████      | 113/275 [1:55:42<1:33:59, 34.81s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01V_34.parquet

Processing parquet files:  41%|████▏     | 114/275 [1:56:02<1:21:13, 30.27s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G05D_133.parquet

Processing parquet files:  42%|████▏     | 115/275 [1:56:23<1:13:35, 27.60s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02K_310.parquet

Processing parquet files:  42%|████▏     | 116/275 [1:57:43<1:54:29, 43.21s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60B_21.parquet

Processing parquet files:  43%|████▎     | 117/275 [1:57:46<1:22:18, 31.26s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B08B_395.parquet

Processing parquet files:  43%|████▎     | 118/275 [1:59:48<2:32:50, 58.41s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A63F_28.parquet

Processing parquet files:  43%|████▎     | 119/275 [1:59:53<1:50:15, 42.41s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G09F_180.parquet

Processing parquet files:  44%|████▎     | 120/275 [2:00:41<1:54:09, 44.19s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47B_232.parquet

Processing parquet files:  44%|████▍     | 121/275 [2:01:49<2:11:45, 51.34s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B01F_157.parquet

Processing parquet files:  44%|████▍     | 122/275 [2:03:11<2:34:10, 60.46s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A23L_151.parquet

Processing parquet files:  45%|████▍     | 123/275 [2:03:15<1:50:20, 43.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16M_288.parquet

Processing parquet files:  45%|████▌     | 124/275 [2:04:27<2:10:37, 51.90s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04C_37.parquet

Processing parquet files:  45%|████▌     | 125/275 [2:04:36<1:38:01, 39.21s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F21K_18.parquet

Processing parquet files:  46%|████▌     | 126/275 [2:05:59<2:09:48, 52.27s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61J_36.parquet

Processing parquet files:  46%|████▌     | 127/275 [2:06:03<1:32:49, 37.63s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B62D_188.parquet

Processing parquet files:  47%|████▋     | 128/275 [2:07:27<2:06:31, 51.64s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16D_47.parquet

Processing parquet files:  47%|████▋     | 129/275 [2:07:31<1:31:05, 37.44s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01P_19.parquet

Processing parquet files:  47%|████▋     | 130/275 [2:07:49<1:16:25, 31.63s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F17D_22.parquet

Processing parquet files:  48%|████▊     | 131/275 [2:08:30<1:22:38, 34.44s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60R_192.parquet

Processing parquet files:  48%|████▊     | 132/275 [2:09:08<1:24:15, 35.35s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01K_267.parquet

Processing parquet files:  48%|████▊     | 133/275 [2:11:19<2:31:28, 64.00s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B01L_45.parquet

Processing parquet files:  49%|████▊     | 134/275 [2:11:33<1:55:43, 49.24s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C22B_29.parquet

Processing parquet files:  49%|████▉     | 135/275 [2:11:34<1:20:54, 34.67s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01N_1000.parquet

Processing parquet files:  49%|████▉     | 136/275 [2:21:13<7:38:45, 198.03s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E05F_20.parquet

Processing parquet files:  50%|████▉     | 137/275 [2:21:14<5:19:23, 138.87s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01Q_128.parquet

Processing parquet files:  50%|█████     | 138/275 [2:21:48<4:05:08, 107.36s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16K_333.parquet

Processing parquet files:  51%|█████     | 139/275 [2:22:43<3:27:38, 91.61s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60P_27.parquet

Processing parquet files:  51%|█████     | 140/275 [2:22:55<2:32:22, 67.72s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E02B_124.parquet

Processing parquet files:  51%|█████▏    | 141/275 [2:23:28<2:08:02, 57.33s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G03G_20.parquet

Processing parquet files:  52%|█████▏    | 142/275 [2:23:37<1:35:12, 42.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F01N_25.parquet

Processing parquet files:  52%|█████▏    | 143/275 [2:23:42<1:09:01, 31.37s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G05B_255.parquet

Processing parquet files:  52%|█████▏    | 144/275 [2:24:03<1:01:56, 28.37s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04B_336.parquet

Processing parquet files:  53%|█████▎    | 145/275 [2:25:57<1:56:57, 53.98s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B21J_27.parquet

Processing parquet files:  53%|█████▎    | 146/275 [2:26:18<1:34:51, 44.12s/it]

正在处理文件: similarity_results_gpu/similiarity_results_D04B_21.parquet

Processing parquet files:  53%|█████▎    | 147/275 [2:26:25<1:10:15, 32.94s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E06B_202.parquet

Processing parquet files:  54%|█████▍    | 148/275 [2:33:13<5:08:04, 145.54s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01B_325.parquet

Processing parquet files:  54%|█████▍    | 149/275 [2:33:45<3:54:00, 111.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B62B_128.parquet

Processing parquet files:  55%|█████▍    | 150/275 [2:35:02<3:30:28, 101.03s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61F_226.parquet

Processing parquet files:  55%|█████▍    | 151/275 [2:35:51<2:57:06, 85.70s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F03D_31.parquet

Processing parquet files:  55%|█████▌    | 152/275 [2:35:59<2:07:46, 62.33s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C23C_141.parquet

Processing parquet files:  56%|█████▌    | 153/275 [2:37:03<2:07:54, 62.91s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C07D_187.parquet

Processing parquet files:  56%|█████▌    | 154/275 [2:37:09<1:31:49, 45.54s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60J_21.parquet

Processing parquet files:  56%|█████▋    | 155/275 [2:37:30<1:16:21, 38.18s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F23D_21.parquet

Processing parquet files:  57%|█████▋    | 156/275 [2:37:38<57:46, 29.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F02B_19.parquet

Processing parquet files:  57%|█████▋    | 157/275 [2:37:41<41:52, 21.29s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04B_170.parquet

Processing parquet files:  57%|█████▋    | 158/275 [2:38:51<1:10:22, 36.09s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C25D_33.parquet

Processing parquet files:  58%|█████▊    | 159/275 [2:38:55<51:07, 26.44s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G08G_48.parquet

Processing parquet files:  58%|█████▊    | 160/275 [2:39:10<44:19, 23.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04N_326.parquet

Processing parquet files:  59%|█████▊    | 161/275 [2:39:49<52:27, 27.61s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23B_173.parquet

Processing parquet files:  59%|█████▉    | 162/275 [2:40:42<1:06:35, 35.36s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02G_241.parquet

Processing parquet files:  59%|█████▉    | 163/275 [2:42:15<1:38:25, 52.73s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G10L_36.parquet

Processing parquet files:  60%|█████▉    | 164/275 [2:42:49<1:26:54, 46.97s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61B_1000.parquet

Processing parquet files:  60%|██████    | 165/275 [2:49:56<4:55:31, 161.19s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E01C_140.parquet

Processing parquet files:  60%|██████    | 166/275 [2:50:31<3:43:32, 123.05s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47J_299.parquet

Processing parquet files:  61%|██████    | 167/275 [2:52:12<3:29:41, 116.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B31B_34.parquet

Processing parquet files:  61%|██████    | 168/275 [2:52:50<2:45:45, 92.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06Q_861.parquet

Processing parquet files:  61%|██████▏   | 169/275 [3:00:52<6:10:26, 209.68s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B05B_197.parquet

Processing parquet files:  62%|██████▏   | 170/275 [3:02:07<4:56:34, 169.47s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65H_369.parquet

Processing parquet files:  62%|██████▏   | 171/275 [3:03:12<3:59:06, 137.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02P_35.parquet

Processing parquet files:  63%|██████▎   | 172/275 [3:03:30<2:55:09, 102.03s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F21V_118.parquet

Processing parquet files:  63%|██████▎   | 173/275 [3:04:10<2:21:53, 83.46s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E21D_119.parquet

Processing parquet files:  63%|██████▎   | 174/275 [3:04:27<1:46:43, 63.40s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06K_40.parquet

Processing parquet files:  64%|██████▎   | 175/275 [3:05:02<1:31:48, 55.08s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C09D_104.parquet

Processing parquet files:  64%|██████▍   | 176/275 [3:05:05<1:04:54, 39.34s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B24B_690.parquet

Processing parquet files:  64%|██████▍   | 177/275 [3:08:36<2:28:08, 90.70s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F25B_50.parquet

Processing parquet files:  65%|██████▍   | 178/275 [3:08:48<1:48:32, 67.14s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02J_359.parquet

Processing parquet files:  65%|██████▌   | 179/275 [3:11:19<2:27:52, 92.43s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60C_19.parquet

Processing parquet files:  65%|██████▌   | 180/275 [3:11:21<1:43:30, 65.38s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04H_216.parquet

Processing parquet files:  66%|██████▌   | 181/275 [3:13:32<2:13:08, 84.98s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01N_2000.parquet

Processing parquet files:  66%|██████▌   | 182/275 [3:23:38<6:13:54, 241.23s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01N_2189.parquet

Processing parquet files:  67%|██████▋   | 183/275 [3:24:51<4:52:27, 190.73s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01M_320.parquet

Processing parquet files:  67%|██████▋   | 184/275 [3:25:30<3:40:20, 145.28s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B23P_244.parquet

Processing parquet files:  67%|██████▋   | 185/275 [3:26:04<2:47:43, 111.81s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B05C_144.parquet

Processing parquet files:  68%|██████▊   | 186/275 [3:26:44<2:14:01, 90.36s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C09K_35.parquet

Processing parquet files:  68%|██████▊   | 187/275 [3:26:48<1:34:25, 64.39s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C12N_222.parquet

Processing parquet files:  68%|██████▊   | 188/275 [3:27:02<1:11:19, 49.19s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65B_354.parquet

Processing parquet files:  69%|██████▊   | 189/275 [3:27:43<1:06:58, 46.73s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G07F_36.parquet

Processing parquet files:  69%|██████▉   | 190/275 [3:27:46<47:38, 33.63s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F28F_18.parquet

Processing parquet files:  69%|██████▉   | 191/275 [3:27:47<33:18, 23.80s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C22C_104.parquet

Processing parquet files:  70%|██████▉   | 192/275 [3:29:49<1:13:40, 53.26s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60N_37.parquet

Processing parquet files:  70%|███████   | 193/275 [3:30:30<1:07:45, 49.58s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01C_162.parquet

Processing parquet files:  71%|███████   | 194/275 [3:30:37<49:54, 36.97s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F27B_37.parquet

Processing parquet files:  71%|███████   | 195/275 [3:30:57<42:23, 31.79s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01M_781.parquet

Processing parquet files:  71%|███████▏  | 196/275 [3:37:17<2:59:34, 136.39s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04M_109.parquet

Processing parquet files:  72%|███████▏  | 197/275 [3:38:19<2:28:04, 113.90s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C08J_26.parquet

Processing parquet files:  72%|███████▏  | 198/275 [3:38:20<1:42:51, 80.14s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C07F_20.parquet

Processing parquet files:  72%|███████▏  | 199/275 [3:38:21<1:11:20, 56.32s/it]

正在处理文件: similarity_results_gpu/similiarity_results_D06B_33.parquet

Processing parquet files:  73%|███████▎  | 200/275 [3:38:28<51:56, 41.55s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01R_674.parquet

Processing parquet files:  73%|███████▎  | 201/275 [3:39:55<1:08:06, 55.22s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H04L_697.parquet

Processing parquet files:  73%|███████▎  | 202/275 [3:40:29<59:24, 48.83s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B07B_186.parquet

Processing parquet files:  74%|███████▍  | 203/275 [3:41:09<55:22, 46.14s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E21F_31.parquet

Processing parquet files:  74%|███████▍  | 204/275 [3:41:12<39:22, 33.27s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B30B_39.parquet

Processing parquet files:  75%|███████▍  | 205/275 [3:41:40<36:50, 31.58s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F24H_48.parquet

Processing parquet files:  75%|███████▍  | 206/275 [3:41:50<28:51, 25.09s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C09J_39.parquet

Processing parquet files:  75%|███████▌  | 207/275 [3:41:53<20:57, 18.49s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B01D_1000.parquet

Processing parquet files:  76%|███████▌  | 208/275 [3:44:48<1:13:06, 65.46s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B03C_25.parquet

Processing parquet files:  76%|███████▌  | 209/275 [3:45:33<1:05:14, 59.31s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01D_116.parquet

Processing parquet files:  76%|███████▋  | 210/275 [3:45:42<48:07, 44.42s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G09B_168.parquet

Processing parquet files:  77%|███████▋  | 211/275 [3:45:59<38:25, 36.03s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01F_125.parquet

Processing parquet files:  77%|███████▋  | 212/275 [3:46:09<29:30, 28.11s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B26D_210.parquet

Processing parquet files:  77%|███████▋  | 213/275 [3:46:55<34:37, 33.51s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B01D_1569.parquet

Processing parquet files:  78%|███████▊  | 214/275 [3:48:36<54:47, 53.89s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61L_132.parquet

Processing parquet files:  78%|███████▊  | 215/275 [3:49:42<57:23, 57.39s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61M_363.parquet

Processing parquet files:  79%|███████▊  | 216/275 [3:53:11<1:41:13, 102.94s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A62C_41.parquet

Processing parquet files:  79%|███████▉  | 217/275 [3:53:20<1:12:25, 74.92s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01N_31.parquet

Processing parquet files:  79%|███████▉  | 218/275 [3:53:35<53:50, 56.68s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01C_112.parquet

Processing parquet files:  80%|███████▉  | 219/275 [3:54:40<55:20, 59.29s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16F_43.parquet

Processing parquet files:  80%|████████  | 220/275 [3:54:44<39:10, 42.75s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47G_120.parquet

Processing parquet files:  80%|████████  | 221/275 [3:55:22<37:09, 41.28s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01L_46.parquet

Processing parquet files:  81%|████████  | 222/275 [3:55:23<25:56, 29.37s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01B_31.parquet

Processing parquet files:  81%|████████  | 223/275 [3:55:31<19:46, 22.81s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04G_300.parquet

Processing parquet files:  81%|████████▏ | 224/275 [3:56:41<31:24, 36.95s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61C_35.parquet

Processing parquet files:  82%|████████▏ | 225/275 [3:57:02<26:46, 32.14s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G01R_857.parquet

Processing parquet files:  82%|████████▏ | 226/275 [3:58:48<44:18, 54.25s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F24F_392.parquet

Processing parquet files:  83%|████████▎ | 227/275 [4:03:26<1:37:10, 121.47s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G07C_37.parquet

Processing parquet files:  83%|████████▎ | 228/275 [4:03:31<1:07:48, 86.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01L_911.parquet

Processing parquet files:  83%|████████▎ | 229/275 [4:10:35<2:23:51, 187.64s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16B_130.parquet

Processing parquet files:  84%|████████▎ | 230/275 [4:11:10<1:46:29, 142.00s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E01H_25.parquet

Processing parquet files:  84%|████████▍ | 231/275 [4:11:31<1:17:31, 105.72s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B65F_45.parquet

Processing parquet files:  84%|████████▍ | 232/275 [4:12:03<59:57, 83.66s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G02B_314.parquet

Processing parquet files:  85%|████████▍ | 233/275 [4:13:37<1:00:45, 86.81s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F26B_243.parquet

Processing parquet files:  85%|████████▌ | 234/275 [4:14:48<55:57, 81.88s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H05K_743.parquet

Processing parquet files:  85%|████████▌ | 235/275 [4:20:40<1:48:33, 162.83s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A62B_18.parquet

Processing parquet files:  86%|████████▌ | 236/275 [4:20:48<1:15:46, 116.58s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B05D_19.parquet

Processing parquet files:  86%|████████▌ | 237/275 [4:20:53<52:35, 83.05s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B22C_33.parquet

Processing parquet files:  87%|████████▋ | 238/275 [4:21:00<37:06, 60.17s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02M_162.parquet

Processing parquet files:  87%|████████▋ | 239/275 [4:21:11<27:19, 45.54s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C08F_39.parquet

Processing parquet files:  87%|████████▋ | 240/275 [4:21:29<21:36, 37.05s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G06N_30.parquet

Processing parquet files:  88%|████████▊ | 241/275 [4:21:49<18:08, 32.01s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G02F_130.parquet

Processing parquet files:  88%|████████▊ | 242/275 [4:22:51<22:32, 40.98s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B25B_275.parquet

Processing parquet files:  88%|████████▊ | 243/275 [4:23:13<18:50, 35.32s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A01D_43.parquet

Processing parquet files:  89%|████████▊ | 244/275 [4:23:34<16:03, 31.08s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61H_168.parquet

Processing parquet files:  89%|████████▉ | 245/275 [4:24:37<20:21, 40.73s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C04B_170.parquet

Processing parquet files:  89%|████████▉ | 246/275 [4:24:47<15:09, 31.37s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C08G_50.parquet

Processing parquet files:  90%|████████▉ | 247/275 [4:24:51<10:49, 23.19s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02S_48.parquet

Processing parquet files:  90%|█████████ | 248/275 [4:25:23<11:35, 25.75s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A45C_25.parquet

Processing parquet files:  91%|█████████ | 249/275 [4:25:48<11:10, 25.78s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B29C_1000.parquet

Processing parquet files:  91%|█████████ | 250/275 [4:37:35<1:35:53, 230.12s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B32B_210.parquet

Processing parquet files:  91%|█████████▏| 251/275 [4:46:45<2:10:21, 325.91s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F27D_38.parquet

Processing parquet files:  92%|█████████▏| 252/275 [4:46:46<1:27:36, 228.56s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E04D_24.parquet

Processing parquet files:  92%|█████████▏| 253/275 [4:46:50<59:06, 161.21s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B25H_110.parquet

Processing parquet files:  92%|█████████▏| 254/275 [4:47:24<43:05, 123.11s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B28B_134.parquet

Processing parquet files:  93%|█████████▎| 255/275 [4:48:13<33:36, 100.84s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16L_314.parquet

Processing parquet files:  93%|█████████▎| 256/275 [4:48:52<26:01, 82.18s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H02H_39.parquet

Processing parquet files:  93%|█████████▎| 257/275 [4:49:30<20:41, 68.98s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A61N_38.parquet

Processing parquet files:  94%|█████████▍| 258/275 [4:50:07<16:50, 59.42s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60H_27.parquet

Processing parquet files:  94%|█████████▍| 259/275 [4:50:22<12:15, 45.96s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01G_28.parquet

Processing parquet files:  95%|█████████▍| 260/275 [4:50:39<09:20, 37.36s/it]

正在处理文件: similarity_results_gpu/similiarity_results_D05B_29.parquet

Processing parquet files:  95%|█████████▍| 261/275 [4:50:41<06:12, 26.62s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A23N_34.parquet

Processing parquet files:  95%|█████████▌| 262/275 [4:50:48<04:32, 20.97s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F25D_132.parquet

Processing parquet files:  96%|█████████▌| 263/275 [4:51:09<04:10, 20.83s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F17C_25.parquet

Processing parquet files:  96%|█████████▌| 264/275 [4:51:29<03:47, 20.69s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F02M_30.parquet

Processing parquet files:  96%|█████████▋| 265/275 [4:51:46<03:13, 19.40s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01B_184.parquet

Processing parquet files:  97%|█████████▋| 266/275 [4:52:18<03:28, 23.18s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F16J_30.parquet

Processing parquet files:  97%|█████████▋| 267/275 [4:52:23<02:21, 17.74s/it]

正在处理文件: similarity_results_gpu/similiarity_results_G03F_25.parquet

Processing parquet files:  97%|█████████▋| 268/275 [4:54:33<05:59, 51.41s/it]

正在处理文件: similarity_results_gpu/similiarity_results_C10G_18.parquet

Processing parquet files:  98%|█████████▊| 269/275 [4:54:33<03:36, 36.13s/it]

正在处理文件: similarity_results_gpu/similiarity_results_F15B_108.parquet

Processing parquet files:  98%|█████████▊| 270/275 [4:55:14<03:07, 37.55s/it]

正在处理文件: similarity_results_gpu/similiarity_results_E03D_18.parquet

Processing parquet files:  99%|█████████▊| 271/275 [4:55:17<01:48, 27.03s/it]

正在处理文件: similarity_results_gpu/similiarity_results_H01F_186.parquet

Processing parquet files:  99%|█████████▉| 272/275 [4:56:58<02:28, 49.35s/it]

正在处理文件: similarity_results_gpu/similiarity_results_A47L_166.parquet

Processing parquet files:  99%|█████████▉| 273/275 [4:57:43<01:35, 47.97s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B64D_27.parquet

Processing parquet files: 100%|█████████▉| 274/275 [4:57:54<00:36, 36.93s/it]

正在处理文件: similarity_results_gpu/similiarity_results_B60T_25.parquet

Processing parquet files: 100%|██████████| 275/275 [4:57:57<00:00, 65.01s/it]

In [6]:
parquet_df = pd.concat(parquet_result_list, ignore_index=True)

In [7]:
parquet_df.to_csv('parquet_result.csv', index=False)

In [17]:
parquet_csv_list = []
# 读取parquet文件为dataframe
for file in tqdm(similarity_csv_files, desc="Processing csv files"):
    tqdm.write(f"正在处理文件: {file}")
    df = pd.read_csv(file)
    df = df[df['patent_id'] != df['similar_patent_id']]
    # 不使用 apply 的替代方案
    # 首先按 patent_id 和 similarity_score 排序
    df_sorted = df.sort_values(['patent_id', 'similarity_score'], ascending=[True, False])
    # 然后使用 groupby 和 head 获取每组前 100 条
    result = df_sorted.groupby('patent_id').head(100).reset_index(drop=True)
    parquet_csv_list.append(result)

In [8]:
parquet_df.shape

(1468672994, 3)

In [9]:
99642574 + 1468672994

1568315568